SUBJECT = 'westcol'
SCROLL_PAUSE_TIME = 3
SCROLL = 1000
SCROLL_SCRIPT = f'window.scrollBy(0, {SCROLL});'
PATH_CHROMEDRIVER = '/home/samargo/Documents/selenium/chromedriver'
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
QUANTITY_TWEETS = 10
NAME_FILE = "out.json"